spring.application.name=backend
spring.data.mongodb.uri=mongodb+srv://pratikshayattinamani_db_user:pR%40tiksha999@cluster0.jsemcbj.mongodb.net/AIIncidentAnalyzer?retryWrites=true&w=majority&appName=Cluster0
logging.level.org.springframework.boot.context.config=DEBUG